package com.sample.rules
import com.sample.*;

rule "Liga alarme se alguem avistado"
salience 100
	when
		$hs: HouseSection()
		$s: Camera(houseSection == $hs, connected == true)
		not Alarm()
		exists Outsider(houseSection == $hs)
	then
		insert(new Alarm());
		System.out.println("Intruso avistado na divisao "+$hs.getSection());
		System.out.println("Alarme Ligado");
	
end


rule "Chama segurança se alguem armado"
salience 98
	when
		$hs: HouseSection()
		$s: Camera(houseSection == $hs, connected == true)
		exists Outsider(houseSection == $hs, armed == true)
	then
		insert(new Security($hs));
		System.out.println("Intruso armado avistado na divisao "+$hs.getSection());	
end



rule "Tudo controlado"
salience 1
	when
		not Alarm()
		//exists Camera(connected == false)
		//exists Sensor(connected == false)
	then
		System.out.println("Tudo controlado");
end
